macro_rules! invoke_handler {
    () => {
        tauri::generate_handler![
            // service
            crate::commands::service::service_start,
            crate::commands::service::service_stop,
            crate::commands::service::service_initialize,
            crate::commands::service::service_rpc_token,
            crate::commands::service::service_sync_codex_models_cache,
            crate::commands::startup::service_startup_snapshot,
            // account
            crate::commands::account::remote::service_account_list,
            crate::commands::account::remote::service_account_delete,
            crate::commands::account::remote::service_account_delete_many,
            crate::commands::account::remote::service_account_delete_by_statuses,
            crate::commands::account::remote::service_account_delete_unavailable_free,
            crate::commands::account::remote::service_account_update,
            crate::commands::account::remote::service_account_warmup,
            crate::commands::account::transfer::service_account_import,
            crate::commands::account::transfer::service_account_import_by_file,
            crate::commands::account::transfer::service_account_import_by_directory,
            crate::commands::account::transfer::service_account_export_by_account_files,
            crate::commands::account::local::local_account_delete,
            // usage
            crate::commands::usage::service_usage_read,
            crate::commands::usage::service_usage_list,
            crate::commands::usage::service_usage_aggregate,
            crate::commands::usage::service_usage_refresh,
            // request log
            crate::commands::requestlog::service_requestlog_list,
            crate::commands::requestlog::service_requestlog_error_list,
            crate::commands::requestlog::service_requestlog_error_clear,
            crate::commands::requestlog::service_requestlog_summary,
            crate::commands::requestlog::service_requestlog_clear,
            crate::commands::requestlog::service_requestlog_today_summary,
            // plugin
            crate::commands::plugin::service_plugin_catalog_list,
            crate::commands::plugin::service_plugin_catalog_refresh,
            crate::commands::plugin::service_plugin_install,
            crate::commands::plugin::service_plugin_update,
            crate::commands::plugin::service_plugin_uninstall,
            crate::commands::plugin::service_plugin_list,
            crate::commands::plugin::service_plugin_enable,
            crate::commands::plugin::service_plugin_disable,
            crate::commands::plugin::service_plugin_tasks_update,
            crate::commands::plugin::service_plugin_tasks_list,
            crate::commands::plugin::service_plugin_tasks_run,
            crate::commands::plugin::service_plugin_logs_list,
            // settings
            crate::commands::settings::service_listen::service_listen_config_get,
            crate::commands::settings::service_listen::service_listen_config_set,
            crate::commands::settings::gateway::service_gateway_route_strategy_get,
            crate::commands::settings::gateway::service_gateway_route_strategy_set,
            crate::commands::settings::gateway::service_gateway_manual_account_get,
            crate::commands::settings::gateway::service_gateway_manual_account_set,
            crate::commands::settings::gateway::service_gateway_manual_account_clear,
            crate::commands::settings::gateway::service_gateway_background_tasks_get,
            crate::commands::settings::gateway::service_gateway_background_tasks_set,
            crate::commands::settings::gateway::service_gateway_concurrency_recommend_get,
            crate::commands::settings::gateway::service_gateway_codex_latest_version_get,
            crate::commands::settings::gateway::service_gateway_upstream_proxy_get,
            crate::commands::settings::gateway::service_gateway_upstream_proxy_set,
            crate::commands::settings::gateway::service_gateway_transport_get,
            crate::commands::settings::gateway::service_gateway_transport_set,
            crate::commands::settings::ui::app_settings_get,
            crate::commands::settings::ui::app_settings_set,
            crate::commands::settings::ui::app_close_to_tray_on_close_get,
            crate::commands::settings::ui::app_close_to_tray_on_close_set,
            // login
            crate::commands::login::service_login_start,
            crate::commands::login::service_login_status,
            crate::commands::login::service_login_complete,
            crate::commands::login::service_login_chatgpt_auth_tokens,
            crate::commands::login::service_account_read,
            crate::commands::login::service_account_logout,
            crate::commands::login::service_chatgpt_auth_tokens_refresh,
            crate::commands::login::service_chatgpt_auth_tokens_refresh_all,
            // api key
            crate::commands::aggregate_api::service_aggregate_api_list,
            crate::commands::aggregate_api::service_aggregate_api_read_secret,
            crate::commands::aggregate_api::service_aggregate_api_create,
            crate::commands::aggregate_api::service_aggregate_api_update,
            crate::commands::aggregate_api::service_aggregate_api_delete,
            crate::commands::aggregate_api::service_aggregate_api_test_connection,
            crate::commands::apikey::service_apikey_list,
            crate::commands::apikey::service_apikey_read_secret,
            crate::commands::apikey::service_apikey_create,
            crate::commands::apikey::service_apikey_models,
            crate::commands::apikey::service_model_catalog_list,
            crate::commands::apikey::service_model_catalog_save,
            crate::commands::apikey::service_model_catalog_delete,
            crate::commands::apikey::service_apikey_usage_stats,
            crate::commands::apikey::service_apikey_update_model,
            crate::commands::apikey::service_apikey_delete,
            crate::commands::apikey::service_apikey_disable,
            crate::commands::apikey::service_apikey_enable,
            // system
            crate::commands::system::open_in_browser,
            crate::commands::system::open_in_file_manager,
            crate::commands::system::app_window_unsaved_draft_sections_set,
            // updater
            crate::commands::updater::app_update_check,
            crate::commands::updater::app_update_prepare,
            crate::commands::updater::app_update_apply_portable,
            crate::commands::updater::app_update_launch_installer,
            crate::commands::updater::app_update_status,
            crate::commands::updater::app_update_open_logs_dir
        ]
    };
}

pub(crate) use invoke_handler;
